name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v2

      - name: Test
        run: xcodebuild test -project iSimUDuck.xcodeproj/ -scheme iSimUDuck -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 8"
